services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: test-zoco-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    networks:
      - app-network
      
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: test-zoco-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
